/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package videoExport

import processing.core.PApplet
import kotlin.test.assertTrue

class VideoExportTest {
    @org.junit.Test
    fun isAvailableMethodReturnsTrue() {
        //val pApplet = PApplet()
        //val classUnderTest = VideoExport(pApplet)

        //assertTrue(classUnderTest.isAvailable(),
        //    ".isAvailable() should return 'true'")

        //classUnderTest.setMovieFileName("file.mp4")

        //assertTrue(classUnderTest.VERSION == "0.2.4", "version seems right")
    }
}
